# GitHub Actions Self-Deploy Workflow
# Builds, tests, and deploys to self-hosted infrastructure via Cloudflare Tunnel
#
# Setup:
# 1. Copy to .github/workflows/deploy.yml
# 2. Add secrets in GitHub repo settings:
#    - DEPLOY_HOST: SSH host (e.g., your-server.example.com)
#    - DEPLOY_USER: SSH username
#    - DEPLOY_KEY: SSH private key
#    - TUNNEL_TOKEN: Cloudflare tunnel token (optional, for tunnel management)
#    - SOPS_AGE_KEY: Age private key (if using SOPS for secrets)

name: Build and Deploy

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]
  workflow_dispatch:
    inputs:
      environment:
        description: 'Deployment environment'
        required: true
        default: 'production'
        type: choice
        options:
          - production
          - staging

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  # ===========================================
  # Build and Test
  # ===========================================
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Container Registry
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: |
            type=ref,event=branch
            type=ref,event=pr
            type=sha,prefix=
            type=raw,value=latest,enable=${{ github.ref == 'refs/heads/main' }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      # Run tests in container
      - name: Run tests
        run: |
          docker run --rm ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ github.sha }} npm test
        if: github.event_name == 'pull_request'

    outputs:
      image_tag: ${{ github.sha }}

  # ===========================================
  # Deploy to Self-Hosted Server
  # ===========================================
  deploy:
    needs: build
    runs-on: ubuntu-latest
    if: github.event_name != 'pull_request'
    environment:
      name: ${{ github.event.inputs.environment || 'production' }}
      url: https://${{ vars.DOMAIN }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # Decrypt secrets if using SOPS
      - name: Decrypt secrets
        if: ${{ secrets.SOPS_AGE_KEY != '' }}
        env:
          SOPS_AGE_KEY: ${{ secrets.SOPS_AGE_KEY }}
        run: |
          curl -LO https://github.com/getsops/sops/releases/download/v3.8.1/sops-v3.8.1.linux.amd64
          chmod +x sops-v3.8.1.linux.amd64
          ./sops-v3.8.1.linux.amd64 -d .env.encrypted > .env

      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.DEPLOY_KEY }}" > ~/.ssh/deploy_key
          chmod 600 ~/.ssh/deploy_key
          ssh-keyscan -H ${{ secrets.DEPLOY_HOST }} >> ~/.ssh/known_hosts

      - name: Deploy to server
        env:
          DEPLOY_HOST: ${{ secrets.DEPLOY_HOST }}
          DEPLOY_USER: ${{ secrets.DEPLOY_USER }}
          IMAGE_TAG: ${{ needs.build.outputs.image_tag }}
        run: |
          ssh -i ~/.ssh/deploy_key ${DEPLOY_USER}@${DEPLOY_HOST} << 'ENDSSH'
            set -e
            cd /opt/app

            # Pull latest image
            docker pull ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${IMAGE_TAG}

            # Run database migrations
            docker run --rm \
              --env-file .env \
              --network app-network \
              ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${IMAGE_TAG} \
              npm run migrate

            # Update running containers
            docker compose pull
            docker compose up -d --remove-orphans

            # Cleanup old images
            docker image prune -f

            # Health check
            sleep 10
            curl -f http://localhost:3000/health || exit 1
          ENDSSH

      - name: Notify on success
        if: success()
        run: |
          echo "✅ Deployed ${{ github.sha }} to ${{ github.event.inputs.environment || 'production' }}"

      - name: Notify on failure
        if: failure()
        run: |
          echo "❌ Deployment failed for ${{ github.sha }}"

  # ===========================================
  # Rollback (Manual Trigger)
  # ===========================================
  rollback:
    runs-on: ubuntu-latest
    if: github.event_name == 'workflow_dispatch' && failure()

    steps:
      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.DEPLOY_KEY }}" > ~/.ssh/deploy_key
          chmod 600 ~/.ssh/deploy_key
          ssh-keyscan -H ${{ secrets.DEPLOY_HOST }} >> ~/.ssh/known_hosts

      - name: Rollback to previous version
        env:
          DEPLOY_HOST: ${{ secrets.DEPLOY_HOST }}
          DEPLOY_USER: ${{ secrets.DEPLOY_USER }}
        run: |
          ssh -i ~/.ssh/deploy_key ${DEPLOY_USER}@${DEPLOY_HOST} << 'ENDSSH'
            set -e
            cd /opt/app

            # Get previous image tag
            PREVIOUS_TAG=$(docker compose config | grep image | head -1 | awk '{print $2}' | cut -d: -f2)

            # Rollback
            docker compose down
            docker compose up -d

            echo "Rolled back to ${PREVIOUS_TAG}"
          ENDSSH

# ===========================================
# Reusable Workflows (Optional)
# ===========================================

# For monorepos, you can use path filters:
# on:
#   push:
#     paths:
#       - 'apps/api/**'
#       - 'apps/web/**'
#       - 'packages/**'

# For scheduled deployments:
# on:
#   schedule:
#     - cron: '0 2 * * *'  # Daily at 2 AM UTC
